import { writeFileSync, existsSync, mkdirSync } from 'fs';
import { join } from 'path';

export interface SessionRecord {
  ts: number;
  tool: string;
  target: string;
  tokens_in: number;
  tokens_saved: number;
  latency_ms: number;
}

export interface ReportData {
  session_id: string;
  date: string;
  totals: { tokens_used: number; tokens_saved: number; reduction: number; cost_saved: number; turns: number };
  files_focused: string[];
}

export function generateReportHTML(data: ReportData): string {
  const badge = `![LoomMCP saves ${data.totals.reduction}%](https://img.shields.io/badge/LoomMCP-saves_${data.totals.reduction}%25-1D9E75)`;
  const tweet = `Just used @LoomMCP: ${data.totals.reduction}% reduction, $${data.totals.cost_saved.toFixed(2)} saved. npx @loom-mcp/server init`;

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>LoomMCP Report — ${data.session_id}</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    :root { --bg: #0D1117; --surface: #161B22; --border: #30363D; --green: #3FB950; --text: #E6EDF3; --muted: #8B949E; }
    body { background: var(--bg); color: var(--text); font-family: -apple-system, sans-serif; padding: 2rem; line-height: 1.5; }
    header { display: flex; justify-content: space-between; margin-bottom: 2rem; border-bottom: 1px solid var(--border); padding-bottom: 1rem; }
    h1 { font-size: 1.25rem; }
    h1 span { color: var(--green); }
    .hero { display: grid; grid-template-columns: repeat(4, 1fr); gap: 1rem; margin-bottom: 2rem; }
    .stat { background: var(--surface); border: 1px solid var(--border); padding: 1.5rem; border-radius: 0.5rem; text-align: center; }
    .stat-value { font-family: 'JetBrains Mono', monospace; font-size: 2rem; font-weight: 700; color: var(--green); }
    .stat-label { font-size: 0.75rem; color: var(--muted); text-transform: uppercase; margin-top: 0.5rem; }
    .section { background: var(--surface); border: 1px solid var(--border); padding: 1.5rem; border-radius: 0.5rem; margin-bottom: 1rem; }
    h2 { font-size: 0.875rem; color: var(--muted); margin-bottom: 1rem; }
    .btn { background: var(--green); color: var(--bg); border: none; padding: 0.75rem 1rem; border-radius: 0.5rem; cursor: pointer; font-size: 0.875rem; }
    .code { background: var(--bg); padding: 1rem; border-radius: 0.5rem; font-family: monospace; font-size: 0.75rem; overflow-x: auto; white-space: pre-wrap; }
    footer { text-align: center; color: var(--muted); font-size: 0.75rem; margin-top: 2rem; padding-top: 1rem; border-top: 1px solid var(--border); }
    footer a { color: var(--green); }
  </style>
</head>
<body>
  <header>
    <h1><span>⚡</span> LoomMCP <span>Session Report</span></h1>
  </header>
  
  <div class="hero">
    <div class="stat"><div class="stat-value">${data.totals.tokens_saved.toLocaleString()}</div><div class="stat-label">Tokens Saved</div></div>
    <div class="stat"><div class="stat-value">$${data.totals.cost_saved.toFixed(2)}</div><div class="stat-label">Cost Saved</div></div>
    <div class="stat"><div class="stat-value">${data.totals.reduction}%</div><div class="stat-label">Reduction</div></div>
    <div class="stat"><div class="stat-value">${data.totals.turns}</div><div class="stat-label">Turns</div></div>
  </div>
  
  <div class="section">
    <h2>Share</h2>
    <button class="btn" onclick="navigator.clipboard.writeText('${badge}')">📋 Copy Badge</button>
    <button class="btn" onclick="navigator.clipboard.writeText('${tweet}')">🐦 Copy Tweet</button>
  </div>
  
  <footer>
    Generated by <a href="https://github.com/loom-mcp/loom-mcp">LoomMCP</a>
  </footer>
</body>
</html>`;
}

export async function saveReport(data: ReportData, outputDir: string = '.loom/reports'): Promise<string> {
  if (!existsSync(outputDir)) {
    mkdirSync(outputDir, { recursive: true });
  }
  const filename = `${data.session_id}.html`;
  writeFileSync(join(outputDir, filename), generateReportHTML(data));
  return filename;
}